steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', 'docker/Dockerfile',
      '-t', 'gcr.io/$PROJECT_ID/etl-sales-pipeline:latest',
      '.'
    ]

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/$PROJECT_ID/etl-sales-pipeline:latest'
    ]
  
images:
  - 'gcr.io/$PROJECT_ID/etl-sales-pipeline:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'
